version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "ArtistMan"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-qwx97xp90pfq"
s3_prefix = "ArtistMan"
region = "eu-central-1"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
