AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  Sample SAM Template for AWS

# More info about Globals: https://github.com/awslabs/serverless-application-model/blob/master/docs/globals.rst
Globals:
  Function:
    Timeout: 10

Resources:

  ArtistMan:
    Type: AWS::Serverless::Api
    Properties:
      StageName: Prod
      Cors: "'*'"
      Auth:
        DefaultAuthorizer: artistAuth1
        Authorizers:
          artistAuth1:
            UserPoolArn: arn:aws:cognito-idp:eu-central-1:845376454911:userpool/eu-central-1_l19y1ueM5

  HelloWorldFunction:
    Type: AWS::Serverless::Function # More info about Function Resource: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction
    Properties:
      CodeUri: ./src/Lambda/
      Handler: Lambda::Lambda.Function::FunctionHandler
      Runtime: dotnetcore2.1
      Environment: # More info about Env Vars: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#environment-object
        Variables:
          PARAM1: VALUE
      Events:
        HelloWorld:
          Type: Api # More info about API Event Source: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#api
          Properties:
            RestApiId: !Ref ArtistMan
            Path: /hello
            Method: get
  GetAllArtist:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: ./src/Lambda/
      Handler: Lambda::Lambda.ArtistService::GetAllArtist
      Runtime: dotnetcore2.1
      Role: arn:aws:iam::845376454911:role/service-role/MessageScan-role-av1nmp7k
      Timeout: 30
      Events:
        TesterEvent:
          Type: Api
          Properties:
            RestApiId: !Ref ArtistMan
            Path: /artist/
            Method: get
  GetArtistById:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: ./src/Lambda/
      Handler: Lambda::Lambda.ArtistService::GetArtistById
      Runtime: dotnetcore2.1
      Role: arn:aws:iam::845376454911:role/service-role/MessageScan-role-av1nmp7k
      Timeout: 30
      Events:
        TesterEvent:
          Type: Api
          Properties:
            RestApiId: !Ref ArtistMan
            Path: /artist/{id}
            Method: get
  GetArtistAlbums:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: ./src/Lambda/
      Handler: Lambda::Lambda.ArtistService::GetArtistAlbums
      Runtime: dotnetcore2.1
      Role: arn:aws:iam::845376454911:role/service-role/MessageScan-role-av1nmp7k
      Timeout: 30
      Events:
        TesterEvent:
          Type: Api
          Properties:
            RestApiId: !Ref ArtistMan
            Path: /artistalbum/{id}
            Method: get
  GetArtistMembers:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: ./src/Lambda/
      Handler: Lambda::Lambda.ArtistService::GetArtistMembers
      Runtime: dotnetcore2.1
      Role: arn:aws:iam::845376454911:role/service-role/MessageScan-role-av1nmp7k
      Timeout: 30
      Events:
        TesterEvent:
          Type: Api
          Properties:
            RestApiId: !Ref ArtistMan
            Path: /artistmembers/{id}
            Method: get

#Outputs:
  # ServerlessRestApi is an implicit API created out of Events key under Serverless::Function
  # Find out more about other implicit resources you can reference within SAM
  # https://github.com/awslabs/serverless-application-model/blob/master/docs/internals/generated_resources.rst#api